services:
  - type: web
    name: science-social-media
    runtime: java17
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/science-social-media-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080

  - type: pgsql
    name: science-db
    plan: free
